version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yarn install

  build:
    commands:
      - echo "Building the React-Vite frontend app..."
      - yarn build

artifacts:
  files:
    - 'dist/**/*'    
  base-directory: dist 
